# Generated by Django 5.2.6 on 2025-09-08 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='ONLY', editable=False, max_length=8, unique=True)),
                ('overhead_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه سربار هر متر (M30)')),
                ('sheet_price_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='فی ورق نقد (M31)')),
                ('sheet_price_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='فی ورق مدت (M33)')),
                ('profit_rate_percent', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='نرخ سود ٪ (I41)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کرایه حمل (E43)')),
                ('pallet_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه پالت\u200cبندی (H43)')),
                ('interface_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه رابط (J43)')),
                ('fixed_widths', models.JSONField(default=list, verbose_name='عرض\u200cهای ثابت ورق (cm)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalcFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='کلید')),
                ('expression', models.TextField(verbose_name='عبارت محاسباتی (Python, امن)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='نام مجموعه/شرکت')),
                ('economic_no', models.CharField(blank=True, max_length=100, verbose_name='شماره اقتصادی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FluteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('C', 'C'), ('E', 'E'), ('B', 'B'), ('CB', 'CB'), ('CE', 'CE'), ('EB', 'EB')], max_length=2, unique=True, verbose_name='گام فلوت')),
                ('glue_machine', models.CharField(blank=True, max_length=100, verbose_name='ماشین چسب')),
                ('be_flute', models.CharField(blank=True, max_length=100, verbose_name='B/E فلوت')),
                ('middle_layer', models.CharField(blank=True, max_length=100, verbose_name='لایه میانی')),
                ('c_flute', models.CharField(blank=True, max_length=100, verbose_name='C فلوت')),
                ('bottom_layer', models.CharField(blank=True, max_length=100, verbose_name='زیره')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='کد محصول (یکتا)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('registered_at', models.DateField(verbose_name='تاریخ ثبت')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('commitment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تعهدی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('in_production', 'در حال تولید'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='قیمت سفارش')),
                ('last_unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='نرخ واحد')),
                ('last_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='فی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='carton_pricing.customer', verbose_name='مشتری')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='برچسب')),
                ('number', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='carton_pricing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='شماره تماس')),
                ('prepared_by', models.CharField(max_length=100, verbose_name='نام تنظیم\u200cکننده')),
                ('has_print_notes', models.CharField(choices=[('yes', 'دارد'), ('no', 'ندارد')], default='no', max_length=3, verbose_name='چاپ و نکات تبدیل')),
                ('dim_customer', models.BooleanField(default=False, verbose_name='ابعاد مشتری')),
                ('dim_customer_sample', models.BooleanField(default=False, verbose_name='نمونه مشتری')),
                ('dim_sample', models.BooleanField(default=False, verbose_name='ابعاد نمونه')),
                ('tech_new_cliche', models.BooleanField(default=False, verbose_name='کلیشه جدید')),
                ('tech_handle_slot', models.BooleanField(default=False, verbose_name='جای دسته')),
                ('tech_punch', models.BooleanField(default=False, verbose_name='پانچ')),
                ('tech_pallet', models.BooleanField(default=False, verbose_name='پالت\u200cکشی')),
                ('tech_shipping_on_customer', models.BooleanField(default=False, verbose_name='هزینه حمل با مشتری')),
                ('product_code', models.CharField(blank=True, max_length=64, verbose_name='کد محصول')),
                ('carton_type', models.CharField(blank=True, max_length=100, verbose_name='نوع کارتن')),
                ('carton_name', models.CharField(blank=True, max_length=150, verbose_name='نام کارتن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('I8_qty', models.PositiveIntegerField(default=1, verbose_name='تیراژ کارتن (I8)')),
                ('A1_layers', models.IntegerField(choices=[(1, '3 لایه'), (2, '5 لایه')], verbose_name='چند لایه (A1)')),
                ('A2_pieces', models.IntegerField(choices=[(1, 'یک تیکه'), (2, 'نیم کارتن'), (3, 'چهار تیکه')], verbose_name='چند تیکه (A2)')),
                ('A3_door_type', models.IntegerField(choices=[(1, 'درب باز'), (2, 'درب بسته'), (3, 'درب دوبل')], verbose_name='نوع درب (A3)')),
                ('A4_door_count', models.IntegerField(choices=[(1, 'دو درب'), (2, 'تک درب')], verbose_name='تعداد درب (A4)')),
                ('E15_len', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='طول (E15, cm)')),
                ('G15_wid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='عرض (G15, cm)')),
                ('I15_hgt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ارتفاع (I15, cm)')),
                ('E17_lip', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='لب درب (E17, cm)')),
                ('payment_type', models.CharField(choices=[('cash', 'نقد'), ('credit', 'اعتباری')], default='cash', max_length=6, verbose_name='بازپرداخت')),
                ('E46_round_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جهت رند کردن (E46)')),
                ('A6_sheet_code', models.IntegerField(default=0, verbose_name='A6 کد شیت')),
                ('E20_industrial_len', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='طول صنعتی (E20, cm)')),
                ('K20_industrial_wid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عرض صنعتی (K20, cm)')),
                ('F24_per_sheet_count', models.PositiveIntegerField(default=1, verbose_name='تعداد هر ورق (F24)')),
                ('chosen_sheet_width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عرض ورق انتخابی (cm)')),
                ('E28_carton_consumption', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='مصرف کارتن (E28)')),
                ('E38_sheet_area_m2', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='متراژ ورق (E38, m²)')),
                ('I38_sheet_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ورق (I38)')),
                ('E41_sheet_working_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مایه کاری ورق (E41)')),
                ('E40_overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مایه کاری سربار (E40)')),
                ('M40_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مایه کاری کلی (M40)')),
                ('M41_profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ سود (M41)')),
                ('I41_profit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نرخ سود ٪ (I41)')),
                ('E43_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کرایه حمل (E43)')),
                ('H43_pallet', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه پالت\u200cبندی (H43)')),
                ('J43_interface', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه رابط (J43)')),
                ('H46_price_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='قیمت نهایی بدون مالیات (H46)')),
                ('J48_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مالیات (J48)')),
                ('E48_price_with_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='قیمت نهایی با مالیات (E48)')),
                ('waste_warning', models.BooleanField(default=False, verbose_name='هشدار دورریز ≥ 11؟')),
                ('note_message', models.CharField(blank=True, max_length=300, verbose_name='پیغام/یادداشت F24')),
                ('D31_flute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carton_pricing.flutestep', verbose_name='گام فلوت (D31)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carton_pricing.customer', verbose_name='سفارش\u200cدهنده')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='فی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carton_pricing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carton_pricing.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='carton_pricing.product', verbose_name='محصولات پرمصرف'),
        ),
    ]
