# Generated by Django 5.2.6 on 2025-09-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesettings',
            name='custom_vars',
            field=models.JSONField(blank=True, default=dict, verbose_name='ثابت\u200cهای سفارشی'),
        ),
    ]
