# carton_pricing/migrations/0003_flutestep_to_fk_and_paper.py
# Generated by Django 4.2.24 on 2025-09-21

from django.db import migrations, models
import django.db.models.deletion


def map_text_to_fk(apps, schema_editor):
    """
    متن‌های قدیمی FluteStep را به Paper نگاشت می‌کند و FKهای جدید را پر می‌کند.
    اگر مقدار متنی خالی/فاصله باشد ⇒ FK = NULL
    """
    FluteStep = apps.get_model("carton_pricing", "FluteStep")
    Paper = apps.get_model("carton_pricing", "Paper")

    def get_paper(name):
        name = (name or "").strip()
        if not name:
            return None
        obj, _ = Paper.objects.get_or_create(name_paper=name)
        return obj

    for fs in FluteStep.objects.all():
        fs.glue_machine = get_paper(getattr(fs, "glue_machine_old", None))
        fs.be_flute     = get_paper(getattr(fs, "be_flute_old", None))
        fs.middle_layer = get_paper(getattr(fs, "middle_layer_old", None))
        fs.c_flute      = get_paper(getattr(fs, "c_flute_old", None))
        fs.bottom_layer = get_paper(getattr(fs, "bottom_layer_old", None))
        fs.save(update_fields=[
            "glue_machine", "be_flute", "middle_layer", "c_flute", "bottom_layer"
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("carton_pricing", "0002_basesettings_custom_vars"),
    ]

    operations = [
        # --- Paper ---
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name_paper", models.CharField("Name_Paper", max_length=120, unique=True)),
            ],
            options={"ordering": ("name_paper",)},
        ),

        # --- Model options (همان‌هایی که داشتی، بدون تغییر معنایی) ---
        migrations.AlterModelOptions(
            name="basesettings",
            options={
                "ordering": ("-updated_at", "-id"),
                "verbose_name": "اطلاعات پایه قیمت‌گذاری",
                "verbose_name_plural": "اطلاعات پایه قیمت‌گذاری",
            },
        ),
        migrations.AlterModelOptions(name="calcformula", options={"ordering": ("key",)}),
        migrations.AlterModelOptions(name="customer", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(name="flutestep", options={"ordering": ("key",)}),
        migrations.AlterModelOptions(name="order", options={"ordering": ("-registered_at", "-id")}),
        migrations.AlterModelOptions(name="orderitem", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(name="phonenumber", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(name="pricequotation", options={"ordering": ("-created_at", "-id")}),
        migrations.AlterModelOptions(name="product", options={"ordering": ("name",)}),

        # --- ایندکس روی TimeStamped ها (همان چیزی که داشتی) ---
        migrations.AlterField(model_name="basesettings", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="basesettings", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="calcformula", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="calcformula", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="customer", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="customer", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="flutestep", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="flutestep", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="order", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="order", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="orderitem", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="orderitem", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="phonenumber", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="phonenumber", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="pricequotation", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="pricequotation", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),
        migrations.AlterField(model_name="product", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True)),
        migrations.AlterField(model_name="product", name="updated_at", field=models.DateTimeField(auto_now=True, db_index=True)),

        # --- محدودیت یکتایی روی PhoneNumber ---
        migrations.AddConstraint(
            model_name="phonenumber",
            constraint=models.UniqueConstraint(fields=("customer", "number"), name="uniq_customer_phone"),
        ),

        # --- مسیر ایمن تبدیل FluteStep از متن به FK ---
        # 1) تغییرنام فیلدهای متنی قدیمی به *_old
        migrations.RenameField("FluteStep", "glue_machine", "glue_machine_old"),
        migrations.RenameField("FluteStep", "be_flute", "be_flute_old"),
        migrations.RenameField("FluteStep", "middle_layer", "middle_layer_old"),
        migrations.RenameField("FluteStep", "c_flute", "c_flute_old"),
        migrations.RenameField("FluteStep", "bottom_layer", "bottom_layer_old"),

        # 2) افزودن فیلدهای FK جدید (nullable)
        migrations.AddField(
            model_name="flutestep",
            name="glue_machine",
            field=models.ForeignKey(
                verbose_name="ماشین چسب",
                to="carton_pricing.paper",
                on_delete=django.db.models.deletion.PROTECT,
                null=True, blank=True, related_name="as_glue_machine",
            ),
        ),
        migrations.AddField(
            model_name="flutestep",
            name="be_flute",
            field=models.ForeignKey(
                verbose_name="B/E فلوت",
                to="carton_pricing.paper",
                on_delete=django.db.models.deletion.PROTECT,
                null=True, blank=True, related_name="as_be_flute",
            ),
        ),
        migrations.AddField(
            model_name="flutestep",
            name="middle_layer",
            field=models.ForeignKey(
                verbose_name="لایه میانی",
                to="carton_pricing.paper",
                on_delete=django.db.models.deletion.PROTECT,
                null=True, blank=True, related_name="as_middle_layer",
            ),
        ),
        migrations.AddField(
            model_name="flutestep",
            name="c_flute",
            field=models.ForeignKey(
                verbose_name="C فلوت",
                to="carton_pricing.paper",
                on_delete=django.db.models.deletion.PROTECT,
                null=True, blank=True, related_name="as_c_flute",
            ),
        ),
        migrations.AddField(
            model_name="flutestep",
            name="bottom_layer",
            field=models.ForeignKey(
                verbose_name="زیره",
                to="carton_pricing.paper",
                on_delete=django.db.models.deletion.PROTECT,
                null=True, blank=True, related_name="as_bottom_layer",
            ),
        ),

        # 3) نگاشت دادهٔ متنی → Paper → پرکردن FKها
        migrations.RunPython(map_text_to_fk, migrations.RunPython.noop),

        # 4) حذف فیلدهای متنی قدیمی
        migrations.RemoveField("FluteStep", "glue_machine_old"),
        migrations.RemoveField("FluteStep", "be_flute_old"),
        migrations.RemoveField("FluteStep", "middle_layer_old"),
        migrations.RemoveField("FluteStep", "c_flute_old"),
        migrations.RemoveField("FluteStep", "bottom_layer_old"),
    ]
