# Generated by Django 5.2.6 on 2025-09-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0003_paper_alter_basesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام گروه')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='flutestep',
            name='be_flute',
        ),
        migrations.RemoveField(
            model_name='flutestep',
            name='bottom_layer',
        ),
        migrations.RemoveField(
            model_name='flutestep',
            name='c_flute',
        ),
        migrations.RemoveField(
            model_name='flutestep',
            name='glue_machine',
        ),
        migrations.RemoveField(
            model_name='flutestep',
            name='middle_layer',
        ),
        migrations.AddField(
            model_name='paper',
            name='grammage_gsm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='گرماژ (gsm)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='unit_amount',
            field=models.CharField(default='1 m²', max_length=50, verbose_name='مقدار واحد'),
        ),
        migrations.AddField(
            model_name='paper',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AddField(
            model_name='paper',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض (cm)'),
        ),
        migrations.AddField(
            model_name='pricequotation',
            name='pq_be_flute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pq_as_be_flute', to='carton_pricing.paper', verbose_name='B/E فلوت'),
        ),
        migrations.AddField(
            model_name='pricequotation',
            name='pq_bottom_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pq_as_bottom_layer', to='carton_pricing.paper', verbose_name='زیره'),
        ),
        migrations.AddField(
            model_name='pricequotation',
            name='pq_c_flute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pq_as_c_flute', to='carton_pricing.paper', verbose_name='C فلوت'),
        ),
        migrations.AddField(
            model_name='pricequotation',
            name='pq_glue_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pq_as_glue_machine', to='carton_pricing.paper', verbose_name='ماشین چسب'),
        ),
        migrations.AddField(
            model_name='pricequotation',
            name='pq_middle_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pq_as_middle_layer', to='carton_pricing.paper', verbose_name='لایه میانی'),
        ),
        migrations.AddField(
            model_name='paper',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='carton_pricing.papergroup', verbose_name='گروه'),
        ),
    ]
