# Generated by Django 5.2.6 on 2025-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0004_papergroup_remove_flutestep_be_flute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='بندهای اضافی به مبلغ')),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ برای نقد')),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ برای مدت\u200cدار')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجبار برای اعمال')),
                ('show_on_invoice', models.BooleanField(default=True, verbose_name='نمایش به عنوان یک بند در فاکتور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
            ],
            options={
                'verbose_name': 'بند اضافی',
                'verbose_name_plural': 'بندهای اضافی',
                'ordering': ('-is_active', 'title'),
            },
        ),
        migrations.AlterField(
            model_name='pricequotation',
            name='A3_door_type',
            field=models.IntegerField(choices=[(1, 'باز/نامتوازن '), (2, 'درب بسته'), (3, 'درب دوبل')], verbose_name='نوع درب (A3)'),
        ),
    ]
