# Generated by Django 5.2.6 on 2025-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0005_extracharge_alter_pricequotation_a3_door_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اختیاری؛ مبلغ به همان واحد پولی قیمت واحد.', max_digits=12, null=True, verbose_name='هزینهٔ حمل'),
        ),
    ]
