# Generated by Django 5.2.6 on 2025-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0006_paper_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequotation',
            name='E18_lip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='لب درب (E18, cm)'),
        ),
    ]
