# Generated by Django 5.2.6 on 2025-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0007_pricequotation_e18_lip'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='Percentage',
            field=models.BooleanField(default=False, verbose_name='محاسبه درصد'),
        ),
        migrations.AlterField(
            model_name='pricequotation',
            name='E17_lip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='لب درب بالا(E17, cm)'),
        ),
        migrations.AlterField(
            model_name='pricequotation',
            name='E18_lip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='لب درب پایین(E18, cm)'),
        ),
    ]
