# Generated by Django 5.2.6 on 2025-09-28 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0008_extracharge_percentage_alter_pricequotation_e17_lip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracharge',
            options={'ordering': ('priority', '-is_active', 'title'), 'verbose_name': 'بند اضافی', 'verbose_name_plural': 'بندهای اضافی'},
        ),
        migrations.AddField(
            model_name='extracharge',
            name='priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='عدد کوچکتر یعنی زودتر محاسبه شود (یکتا).', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='اولویت محاسبه'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='Percentage',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، مقدار نقد/مدت به\u200cعنوان درصد از مبلغ پایه در نظر گرفته می\u200cشود.', verbose_name='محاسبه درصد'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ برای نقد'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ برای مدت\u200cدار'),
        ),
        migrations.AddConstraint(
            model_name='extracharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cash__gte', 0)), name='extracharge_amount_cash_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='extracharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_credit__gte', 0)), name='extracharge_amount_credit_gte_0'),
        ),
    ]
