# Generated by Django 5.2.6 on 2025-09-28 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0009_alter_extracharge_options_extracharge_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='سلفون،تسمه پالت،تسمه کارت،مرکب،منگنه', max_length=120, unique=True, verbose_name='نام هزینه')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ به واحد پولی سیستم؛ نمی\u200cتواند منفی باشد.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینهٔ واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
            ],
            options={
                'verbose_name': 'آیتم هزینهٔ سربار',
                'verbose_name_plural': 'موارد هزینهٔ سربار',
                'ordering': ('-is_active', 'name'),
            },
        ),
    ]
