# Generated by Django 5.2.6 on 2025-09-29 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0010_overheaditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flutestep',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='overheaditem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ به واحد پولی سیستم؛ نمی\u200cتواند منفی باشد.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینهٔ واحد'),
        ),
    ]
