# Generated by Django 5.2.6 on 2025-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0011_alter_flutestep_options_alter_overheaditem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricequotation',
            name='carton_type',
            field=models.CharField(blank=True, choices=[('معمولی', 'معمولی'), ('دایکات', 'دایکات'), ('کفی', 'کفی')], max_length=10, verbose_name='نوع کارتن'),
        ),
    ]
