# Generated by Django 5.2.6 on 2025-10-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0012_alter_pricequotation_carton_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calcformula',
            options={'ordering': ('key',), 'verbose_name': 'فرمول محاسباتی', 'verbose_name_plural': 'فرمول\u200cهای محاسباتی'},
        ),
    ]
