# Generated by Django 5.2.6 on 2025-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0013_alter_calcformula_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequotation',
            name='rahkaran_invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شماره فاکتور راهکاران'),
        ),
    ]
