# Generated by Django 5.2.6 on 2025-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0014_pricequotation_rahkaran_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='overheaditem',
            name='basis',
            field=models.CharField(choices=[('m2', 'بر اساس متراژ ورق (E38)'), ('sheet', 'بر اساس تعداد ورق (I38)')], default='m2', max_length=10, verbose_name='مبنای محاسبه'),
        ),
    ]
