# Generated by Django 5.2.6 on 2025-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton_pricing', '0015_overheaditem_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequotation',
            name='overhead_meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='اطلاعات تکمیلی هزینه\u200cهای سربار'),
        ),
    ]
